name: PR Code Review Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Post Automated Review
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_APP_ID }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
          -d '{
            "body": "🚀 **Code Review Bot:** \n Your PR looks great! Consider refactoring function X for better efficiency. 👍"
          }'
